services:
  db:
    image: mysql:8.4
    working_dir: /workspace
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - db_data:/var/lib/mysql
      - ./backups/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    ports:
      - 8080:8080
      
volumes:
  db_data:
